"""ReactiveGraph — reactive execution engine.

The Python package binds the Node Driver over the versioned RGP/1 protocol and
exposes the native reactive graph API. Build graphs with:

* high-level ``ReactiveGraph.build`` / ``GraphBuilder`` (task / computed / on /
  scope), with ``invoke`` executing through a Driver host or an in-process
  fallback;
* function/decorator workflows via ``functask`` / ``entrypoint`` /
  ``build_function_graph``.

State is transactional (``TrackedState``/``TrackedStateProxy``) and observable
through the scheduler trace. ``DriverHost`` manages the Node Driver subprocess.
"""

from reactivegraph._protocol_version import PROTOCOL_NAME, PROTOCOL_VERSION
from reactivegraph.channels import (
    BaseChannel,
    BinaryOperatorAggregate,
    DeltaChannel,
)
from reactivegraph.checkpoint import (
    BaseCheckpointSaver,
    CheckpointStore,
    CheckpointTuple,
    MemoryCheckpointSaver,
    PendingWrite,
    PostgresCheckpointSaver,
    SqliteCheckpointSaver,
    empty_checkpoint,
    get_checkpointer,
    reset_checkpointer,
    uuid6,
)
from reactivegraph.constants import (
    END,
    REMOVE_ALL_MESSAGES,
    START,
    TAG_HIDDEN,
    TAG_NOSTREAM,
)
from reactivegraph.create_agent import (
    AgentGraph,
    UnsupportedStreamModeError,
    create_agent,
)
from reactivegraph.errors import (
    EmptyChannelError,
    ErrorCode,
    GraphBubbleUp,
    GraphInterrupt,
    GraphRecursionError,
    InvalidUpdateError,
    ParentCommand,
    create_error_message,
)
from reactivegraph.functional import (
    EntrypointPlan,
    FunctionTask,
    build_function_graph,
    entrypoint,
    functask,
)
from reactivegraph.graph import (
    ComputedDef,
    GraphBuilder,
    GraphBuildError,
    GraphDef,
    ReactiveGraph,
    TaskDef,
    TaskOutcome,
)
from reactivegraph.host import (
    DriverError,
    DriverHost,
    sanitize_traceback,
)
from reactivegraph.message_state import EphemeralValue, add_messages
from reactivegraph.messages import (
    AIMessage,
    AIMessageChunk,
    AnyMessage,
    BaseMessage,
    BaseMessageChunk,
    ChatMessage,
    HumanMessage,
    HumanMessageChunk,
    RemoveMessage,
    SystemMessage,
    SystemMessageChunk,
    ToolCall,
    ToolCallChunk,
    ToolMessage,
    ToolMessageChunk,
    add_usage,
    convert_to_messages,
    get_buffer_string,
    message_chunk_to_message,
    message_to_dict,
    messages_from_dict,
    messages_to_dict,
    subtract_usage,
)
from reactivegraph.middleware import (
    AgentMiddleware,
    AgentState,
    ExtendedModelResponse,
    InputAgentState,
    ModelCallResult,
    ModelRequest,
    ModelResponse,
    OmitFromInput,
    OmitFromOutput,
    OmitFromSchema,
    OutputAgentState,
    PrivateStateAttr,
    ToolCallRequest,
    ToolCallWrapper,
    ToolRuntime,
    after_agent,
    after_model,
    before_agent,
    before_model,
    dynamic_prompt,
    hook_config,
    wrap_model_call,
    wrap_tool_call,
)
from reactivegraph.prebuilt import (
    AgentIterationError,
    ReactiveAgent,
    ToolSpec,
    create_react_agent,
)
from reactivegraph.runtime import (
    Runtime,
    get_config,
    get_runtime,
    get_stream_writer,
    runtime_context,
)
from reactivegraph.state import TrackedState, TrackedStateProxy
from reactivegraph.state_graph import CompiledStateGraph, StateGraph
from reactivegraph.store import (
    BaseStore,
    InvalidNamespaceError,
    Item,
    MemoryStore,
    PostgresStore,
    SearchItem,
    SqliteStore,
    get_store,
    reset_store,
)
from reactivegraph.summarization import SummarizationMiddleware
from reactivegraph.todo import (
    PlanningState,
    Todo,
    TodoListMiddleware,
)
from reactivegraph.tool_node import (
    INVALID_TOOL_NAME_ERROR_TEMPLATE,
    TOOL_CALL_ERROR_TEMPLATE,
    TOOL_EXECUTION_ERROR_TEMPLATE,
    TOOL_INVOCATION_ERROR_TEMPLATE,
    InjectedState,
    InjectedStore,
    ToolCallWithContext,
    ToolInvocationError,
    ToolNode,
    msg_content_output,
    tools_condition,
)
from reactivegraph.tools import (
    BaseTool,
    InjectedToolArg,
    InjectedToolCallId,
    SchemaAnnotationError,
    StructuredTool,
    ToolException,
    convert_to_openai_function,
    convert_to_openai_tool,
    create_schema_from_function,
    tool,
)
from reactivegraph.types import Checkpointer, Command, Interrupt, Overwrite, Send

__version__ = "0.1.0"

__all__ = (
    "PROTOCOL_NAME",
    "PROTOCOL_VERSION",
    "__version__",
    "GraphBuilder",
    "GraphDef",
    "ReactiveGraph",
    "TaskDef",
    "ComputedDef",
    "GraphBuildError",
    "TaskOutcome",
    "AgentGraph",
    "create_agent",
    "UnsupportedStreamModeError",
    "Interrupt",
    "GraphInterrupt",
    "Command",
    "Overwrite",
    "Send",
    "Checkpointer",
    "ErrorCode",
    "GraphBubbleUp",
    "GraphRecursionError",
    "EmptyChannelError",
    "InvalidUpdateError",
    "ParentCommand",
    "create_error_message",
    "BaseChannel",
    "BinaryOperatorAggregate",
    "DeltaChannel",
    "Runtime",
    "get_config",
    "get_runtime",
    "get_stream_writer",
    "runtime_context",
    "START",
    "END",
    "TAG_HIDDEN",
    "TAG_NOSTREAM",
    "REMOVE_ALL_MESSAGES",
    "FunctionTask",
    "EntrypointPlan",
    "functask",
    "entrypoint",
    "build_function_graph",
    "DriverHost",
    "DriverError",
    "sanitize_traceback",
    "ToolSpec",
    "ToolNode",
    "Todo",
    "TodoListMiddleware",
    "PlanningState",
    "ToolCallWithContext",
    "InjectedState",
    "InjectedStore",
    "ToolInvocationError",
    "msg_content_output",
    "tools_condition",
    "INVALID_TOOL_NAME_ERROR_TEMPLATE",
    "TOOL_CALL_ERROR_TEMPLATE",
    "TOOL_EXECUTION_ERROR_TEMPLATE",
    "TOOL_INVOCATION_ERROR_TEMPLATE",
    "ReactiveAgent",
    "create_react_agent",
    "AgentIterationError",
    "TrackedState",
    "TrackedStateProxy",
    "StateGraph",
    "SummarizationMiddleware",
    "CompiledStateGraph",
    "AIMessage",
    "AIMessageChunk",
    "AnyMessage",
    "BaseMessage",
    "BaseMessageChunk",
    "ChatMessage",
    "HumanMessage",
    "HumanMessageChunk",
    "RemoveMessage",
    "SystemMessage",
    "SystemMessageChunk",
    "ToolCall",
    "ToolCallChunk",
    "ToolMessage",
    "ToolMessageChunk",
    "add_messages",
    "add_usage",
    "convert_to_messages",
    "get_buffer_string",
    "message_chunk_to_message",
    "message_to_dict",
    "messages_from_dict",
    "messages_to_dict",
    "subtract_usage",
    "EphemeralValue",
    "AgentMiddleware",
    "AgentState",
    "InputAgentState",
    "OutputAgentState",
    "ModelRequest",
    "ModelResponse",
    "ExtendedModelResponse",
    "ModelCallResult",
    "OmitFromInput",
    "OmitFromOutput",
    "OmitFromSchema",
    "PrivateStateAttr",
    "ToolCallRequest",
    "ToolCallWrapper",
    "ToolRuntime",
    "before_model",
    "after_model",
    "before_agent",
    "after_agent",
    "dynamic_prompt",
    "hook_config",
    "wrap_model_call",
    "wrap_tool_call",
    "BaseTool",
    "StructuredTool",
    "ToolException",
    "SchemaAnnotationError",
    "InjectedToolArg",
    "InjectedToolCallId",
    "create_schema_from_function",
    "convert_to_openai_function",
    "convert_to_openai_tool",
    "tool",
    "CheckpointStore",
    "CheckpointTuple",
    "MemoryCheckpointSaver",
    "PostgresCheckpointSaver",
    "SqliteCheckpointSaver",
    "BaseCheckpointSaver",
    "PendingWrite",
    "empty_checkpoint",
    "uuid6",
    "get_checkpointer",
    "reset_checkpointer",
    "InvalidNamespaceError",
    "Item",
    "BaseStore",
    "MemoryStore",
    "PostgresStore",
    "SqliteStore",
    "SearchItem",
    "get_store",
    "reset_store",
)
